- docs/README.md
Fix broken links in README.md which did not work due to README.md not being in root directory. Links to other documents (such as examples and license) are now absolute instead of relative which works regardless of the location of the README.md.
> Fix broken links in README.md

- llm-chain-tools/src/tool_prompt_prefix.txt
- llm-chain-tools/src/tools/mod.rs
- llm-chain-tools/src/tools/python.rs
This tool is a simple wrapper around the Python interpreter. It invokes
Python code and returns the result. The Python code is passed as a string
to the Python interpreter and is executed using `python3 -c`
> Add a Python tool for LLM-chain.

- llm-chain-llama/sys/build.rs
in llama.cpp repo, "-fPIC" flags only exist in on Makefile, but were not included in CMakeLists.txt.
This will fix compilation error on Linux.
> fix: cross compilation error on Mac/Linux

- .gitignore
- llm-chain-llama/src/executor.rs
- llm-chain-llama/src/output.rs
- llm-chain-openai/src/chatgpt/executor.rs
- llm-chain-openai/src/chatgpt/mod.rs
- llm-chain-openai/src/chatgpt/output.rs
- llm-chain/Cargo.toml
- llm-chain/src/chains/map_reduce.rs
- llm-chain/src/chains/sequential.rs
- llm-chain/src/lib.rs
- llm-chain/src/output.rs
- llm-chain/src/parameters.rs
- llm-chain/src/templates.rs
- llm-chain/src/traits.rs
By separating the output into its own trait we reduce the amount of
code that needs to be duplicated between the different models.
To accomplish this we made the assumption that models ought to return
strings in general. This is a reasonable assumption given what LLMs are.
> feat: Separate the output into its own trait.

- Cargo.lock
- llm-chain-llama/examples/alpaca.rs
- llm-chain-openai/examples/qdrant_vectorstore.rs
- llm-chain-openai/examples/similarity_search.rs
- llm-chain-openai/src/embeddings.rs
- llm-chain/Cargo.toml
- llm-chain/src/lib.rs
- llm-chain/src/schema.rs
- llm-chain/src/traits.rs
- llm-chain/src/vectorstores/qdrant.rs
Add similarity_search to VectorStore trait
Add schema.rs with generic Document definition
Add EmptyMetadata as default metadata type for Document to make prototyping easier for library users
Implement similarity_search for Qdrant Vectorstore
Example of similarity_search for Qdrant Vectorstore
Add embed_query to Embeddings trait
Implement embed_query for OpenAI
> Feature: Similarity search

- llm-chain-llama/src/context.rs
- llm-chain-llama/sys/src/bindings.rs
Not sure how to up the cargo.toml version without forcing upping versions along the whole repo
> chore: use new version of llama.cpp for llama-sys

- Cargo.lock
- llm-chain-openai/Cargo.toml
- llm-chain-openai/examples/simple_agent.rs
- llm-chain-openai/examples/simple_invocation.rs
- llm-chain/examples/multitool.rs
- llm-chain/examples/tools_prompt.rs
- llm-chain/src/tools/collection.rs
- llm-chain/src/tools/description.rs
- llm-chain/src/tools/mod.rs
- llm-chain/src/tools/multitool.rs
- llm-chain/src/tools/multitool_default.rs
- llm-chain/src/tools/tool.rs
- llm-chain/src/tools/tools/bash.rs
- llm-chain/src/tools/tools/exit.rs
- llm-chain/src/tools/tools/mod.rs
- llm-chain/src/tools/tools/python.rs
- add multitool macro for combining Tools into a Tool enum
- use multitolol macro as a way of building type-safe ToolCollections with library- and user- defined Tools 
- add a default multitool that combines all library-defined tools; configure it as an optional feature
- remove unwrap() calls in tools, use Results where necessary
Before writing multitool!, I considered using https://docs.rs/enum_dispatch/latest/enum_dispatch/
Unfortunately, it cannot and will not handle associated types (it's mentioned in one of the issues in the project repo), as it's much too complex of a feature to do in a generic way, but not that hard to do for our specific case
> Improvement: Error handling in tools

- llm-chain-llama/src/executor.rs
- llm-chain-llama/src/text_splitter.rs
- llm-chain-openai/src/chatgpt/executor.rs
- llm-chain-openai/src/chatgpt/step.rs
- llm-chain/src/chains/map_reduce.rs
- llm-chain/src/tokens.rs
- llm-chain/src/traits.rs
Hey Will.
Tried to implement the last part of my previous PR,  actually using TextSplitters to chunk Paremeters that are too large for model context.
I'm not sure if this the direction you imagined, but I'm happy to do any changes needed.
> Use text splitter for chunking docs

- llm-chain-openai/Cargo.toml
- llm-chain-openai/examples/qdrant_vectorstore.rs
- llm-chain-openai/examples/similarity_search.rs
- llm-chain-openai/examples/simple_agent.rs
- llm-chain-openai/examples/simple_invocation.rs
- llm-chain-openai/examples/vectorstore_tool_invocation.rs
- llm-chain-openai/src/chatgpt/prompt.rs
- llm-chain/examples/multitool.rs
- llm-chain/src/parameters.rs
- llm-chain/src/tools/collection.rs
- llm-chain/src/tools/multitool.rs
- llm-chain/src/tools/multitool_default.rs
- llm-chain/src/tools/tool.rs
- llm-chain/src/tools/tools/bash.rs
- llm-chain/src/tools/tools/exit.rs
- llm-chain/src/tools/tools/mod.rs
- llm-chain/src/tools/tools/python.rs
- llm-chain/src/tools/tools/vectorstore.rs
- llm-chain/src/traits.rs
- llm-chain/src/vectorstores/qdrant.rs
Make Tool invocations async to accomodate calling VectorStore methods in Tool; remove gen_invoke_function! as inline macros do not work with async_trait; move invoke_typed() into Tool trait; add Input and Output associated types to multitool! macro; adjust examples; WIP: conflicting implementations for QdrantTool - try implementing VectorStore in llm-chain-openai for concrete Embeddings
FIXES:
- prompt parameters were not passed to ChatGPT executor
> Feature: Vectorstore tool

- llm-chain-openai/src/chatgpt/output.rs
- llm-chain-openai/src/chatgpt/output/stream.rs
Refactor openai module's Ouput stream variant to overwrite the stream during primary choices call such that the method can be invoked many times.
> OpenAI streaming update

- llm-chain/src/prompt/string_template/tera.rs
We can use Tera::one_off instead. 
Anything to consider?
> improvement: remove global var TERA

- llm-chain/src/parameters.rs
Some frameworks (like Axum) require Send + Sync futures.
There appears no reason why they would ever be not Send + Sync.
> Impl Send + Sync for Param & ParamFull

- llm-chain-llama/src/executor.rs
- llm-chain-openai/src/chatgpt/executor.rs
- llm-chain/src/agents/self_ask_with_search.rs
- llm-chain/src/chains/map_reduce.rs
- llm-chain/src/prompt/string_template/tera.rs
- llm-chain/src/tokens.rs
- llm-chain/src/traits.rs
Autoescpaing for tera turned off. Resulted in inconsistent token counts.
base_parameters added to prompt when counting tokens used.
answer_prefix is injected into tokens used if using Chat(_) in llama models.
Note: We're currently not supporting templated documents.
> Fix: map-reduce failing

- llm-chain-llama/src/executor.rs
- llm-chain-openai/src/chatgpt/executor.rs
- llm-chain/src/agents/self_ask_with_search.rs
- llm-chain/src/chains/conversation.rs
- llm-chain/src/frame.rs
- llm-chain/src/traits.rs
I was trying out chat streaming and realized it didn't work - `Output.as_stream` was returning None. Decided to find the issue and fix. I am very new to Rust so do guide me on what I am missing to get the PR merged.
Alternatively, if the design is not what was intended, feel free to explain and reject the PR.
> Add is_streaming to create_chat_completion_request

- docs/README.md
It was 0.8.0, updated to 0.11.1.
> docs: Update the version in  README, "Getting Started" section

- crates/llm-chain-openai/src/embeddings.rs
As per title, this allows overriding of the async-openai client for embedding use case.
> Implement Embeddings::for_client for llm-chain-openai

- Cargo.lock
- crates/llm-chain-openai/Cargo.toml
- crates/llm-chain-openai/src/chatgpt/options.rs
- crates/llm-chain-openai/src/chatgpt/text_splitter.rs
Use https://crates.io/crates/strum for the FromStr implementation, and include a few useful overrides that make it easy to specify a model from a user provided string.
Note: strum contains a ToString implementation too, but it doesn't currently handle writing the contents of a default Tuple-like enum (`Model::Other(String)`), but there is a PR for fixing that at:
- https://github.com/Peternator7/strum/pull/270
> chore(openai): add all openai models to Model enum

- crates/llm-chain-hnsw/examples/dump_load.rs
- crates/llm-chain-hnsw/examples/similarity_search.rs
- crates/llm-chain-hnsw/src/lib.rs
- crates/llm-chain/src/document_stores/document_store.rs
- crates/llm-chain/src/document_stores/in_memory_document_store.rs
- No longer force document store to have an id of type usize, only hnsw vector store should use usize
- Wrap embedding ref in an Arc
> [hnsw] Allow more flexibility in id generation for document stores

- crates/llm-chain-llama-sys/src/bindings.rs
- crates/llm-chain-llama/examples/simple.rs
- crates/llm-chain-llama/src/context.rs
- crates/llm-chain-llama/src/executor.rs
- crates/llm-chain-llama/src/options.rs
update code for https://github.com/ggerganov/llama.cpp/pull/1509  and fix executor.
> Update to support the new llama.cpp and fix executor bug

- crates/llm-chain-llama/src/options.rs
- crates/llm-chain/src/options.rs
I didn't see any way to set the number of layers passed to the gpu for llama. I don't know rust so this might be the wrong way to do things.
After setting the enabling the `cuda` feature for `llm-chain-llama-sys` then setting `NumGpuLayers` option to any number above 0 cuda acceleration works perfectly for me and llama models run like 5x faster at 20 layers.
It doesn't seem to break anything as setting the option with `cuda` disabled just has no effect.
>  Opt for num_gpu_layers

- crates/llm-chain-llama-sys/build.rs
I assume this is a typo? Looks like you were planning to use whisper.cpp and switch to llama.cpp, or am I missing the link between whisper and llama?
> Fix llama-sys error message typo

- crates/llm-chain-local/examples/simple.rs
The example is named `simple` instead of `inference`.
> Fix typo in CLI usage message

- crates/llm-chain-mock/Cargo.toml
- crates/llm-chain-mock/README.md
- crates/llm-chain-mock/examples/simple.rs
- crates/llm-chain-mock/src/executor.rs
- crates/llm-chain-mock/src/lib.rs
- crates/llm-chain/src/executor.rs
- crates/llm-chain/src/tokens.rs
Running a real LLM locally or use a paid API is costly. For quick testing and debugging, this mock driver simulates a real LLM but is much faster and cheaper to run.
This implements a LLM executor that only echos your prompt and options back.
> Mock LLM driver

- crates/llm-chain-llama/src/context.rs
- crates/llm-chain-llama/src/executor.rs
Fixes
https://github.com/sobelio/llm-chain/issues/187
[Handle this specific utf8 error](https://doc.rust-lang.org/std/str/struct.Utf8Error.html#method.error_len)
`None: the end of the input was reached unexpectedly. self.valid_up_to() is 1 to 3 bytes from the end of the input. If a byte stream (such as a file or a network socket) is being decoded incrementally, this could be a valid char whose UTF-8 byte sequence is spanning multiple chunks.`
The LLaMA `Executor` cuts off at arbitrary bytes which works for ascii but not multi-byte utf8. Add a buffer that will keep the extra bytes until the next chunk comes in where it will prepend it and add the missing bytes back onto it. It will also replace actually broken utf-8 (not just cut off) with the `std::char::REPLACEMENT_CHARACTER` instead of …
> LLaMA handling unicode

- docs/README.md
- website/docs/getting-started-tutorial/01-setting-up-a-project.md
Using 1.64.0 or below will result in errors about unstable features or unsupported dependencies.
> doc: added minimum Rust version info

- crates/llm-chain-milvus/src/lib.rs
Set an unused variable to another type just to make the project build not fail
> make project buildable

- crates/llm-chain/src/traits.rs
This commit renames the parameter name in the comment to match the actual parameter name.
> fix: rename executor_options to options in comment

- Cargo.lock
- crates/llm-chain-local/src/executor.rs
- crates/llm-chain-milvus/Cargo.toml
- crates/llm-chain-openai/examples/self_ask_with_google_search.rs
- crates/llm-chain-openai/src/chatgpt/executor.rs
- crates/llm-chain/examples/google_serper.rs
- crates/llm-chain/src/chains/map_reduce.rs
- crates/llm-chain/src/options.rs
- crates/llm-chain/src/tools/tools/google_serper.rs
- crates/llm-chain/src/tools/tools/mod.rs
This commit adds a new tool that can be used to search the internet for information similar to BingSearch. The tool uses the Google Serper API to perform the search.
----
Example output from `crates/llm-chain-openai/examples/self_ask_with_google_search.rs`:
```console
$ cargo r --example self_ask_with_google_search
Compiling llm-chain-openai v0.12.3 (/home/danielbevenius/work/ai/llm-chain/crates/llm-chain-openai)
Finished dev [unoptimized + debuginfo] target(s) in 5.04s
Running `target/debug/examples/self_ask_with_google_search`
Are followup questions needed here: Yes. 
Follow up: Where was Levy Mwanawasa born?
Intermediate answer: Levy Mwanawasa was a member of the Lenje tribe and was educated at Chiwala Secondary School in Ndola. He read law at the University of Zambia in Lusaka from …
```
> feat: add google serper (search) tool

- crates/llm-chain-llama/src/executor.rs
If I understand correctly:
Before, the `spawn_blocking` was actually returning another function that was async which would then get awaited which undoes the whole purpose of the `spawn_blocking`.
The async doesn't work that well since it doesn't have any `await`s other than the one locking the mutex, and I couldn't figure out how to get that to work in `spawn_blocking` so now it's changed to `blocking_lock`. 
Also now join handle doesn't get awaited so if the thread panics it doesn't really handle it (I think the mutex lock can also get messed up with a panicked thread?), I don't know the proper way do deal with that.
> stop llama executor blocking

- crates/llm-chain-llama/src/executor.rs
- crates/llm-chain/src/prompt/model.rs
This commit renames the MessageOrText enum to Data in the doc comments for the map method.
> fix: rename MessageOrText to Data in doc comments

- .github/workflows/cicd.yaml
- Cargo.lock
- crates/llm-chain-hnsw/Cargo.toml
- crates/llm-chain-hnsw/examples/dump_load.rs
- crates/llm-chain-hnsw/src/lib.rs
- crates/llm-chain-llama-sys/README.md
- crates/llm-chain-llama-sys/build.rs
- crates/llm-chain-llama-sys/src/bindings.rs
- crates/llm-chain-llama/examples/alpaca.rs
- crates/llm-chain-llama/examples/few_shot.rs
- crates/llm-chain-llama/examples/map_reduce_llama.rs
- crates/llm-chain-llama/examples/simple_llama.rs
- crates/llm-chain-llama/examples/stream.rs
- crates/llm-chain-llama/src/batch.rs
- crates/llm-chain-llama/src/context.rs
- crates/llm-chain-llama/src/executor.rs
- crates/llm-chain-llama/src/lib.rs
- crates/llm-chain-llama/src/model.rs
- crates/llm-chain-llama/src/options.rs
- crates/llm-chain-llama/src/tokenizer.rs
- crates/llm-chain/src/options.rs
- crates/llm-chain/src/traits.rs
This commit updates llama.cpp to the latest/later version.
The motivation for this is that the current version of llama.cpp is a little outdated and there have been changes to the llama.cpp API and also the model format. Currently it is not possible to use the new GGUF format and many of the available models are in this new format which can make it challenging to use this crate at the moment.
The following changes have been made:
* update llama.cpp to latest version using git submodule update --remote --merge llama.cpp
* Manually copied the generated bindings.rs file from the target directory to the src directory. Hope this was the correct thing to do.
* Updated the llm-chain-llama crate to use llama_decode instead of llm_eval which has now been deprecated.
* ~A number of TODOs have been …
> llama: update llama.cpp to latest version

- crates/llm-chain-llama-sys/README.md
- crates/llm-chain-llama-sys/build.rs
This commit adds a flag that can be used to save the generated bindings to the src directory instead of always saving them.
The motivation for this is one might not want to save the bindings on every build which is kind of annoying (sorry about this).
> chore: add flag to save bindings to src directory

- Cargo.lock
- crates/llm-chain-llama/Cargo.toml
- crates/llm-chain-llama/examples/simple_embeddings.rs
- crates/llm-chain-llama/src/batch.rs
- crates/llm-chain-llama/src/context.rs
- crates/llm-chain-llama/src/embeddings.rs
- crates/llm-chain-llama/src/executor.rs
- crates/llm-chain-llama/src/lib.rs
- crates/llm-chain-qdrant/Cargo.toml
- crates/llm-chain-qdrant/examples/similarity_search_llama.rs
- crates/llm-chain/src/traits.rs
This commit adds the ability to generate embeddings using the llama.
The motivation for this is to be able to use llama for embeddings in combination with a vector store, like Qdrant.
This commit also adds an example that demonstrates how to use the llm-chain-llama crate for generating embeddings and then use the Qdrant vector store for storing and searching for similar documents.
____
Example of running simliarity_search_llama:
```console
env LLM_CHAIN_MODEL=~/work/ai/llama.cpp/models/llama-2-7b-chat.Q4_0.gguf cargo r --release --example similarity_search_llama
Finished release [optimized] target(s) in 0.14s
Running `/home/danielbevenius/work/ai/llm-chain/target/release/examples/similarity_search_llama`
llama_model_loader: loaded meta data with 19 key-value pairs and 291 tensors from
... …
```
> llama: add Embeddings for llama

- crates/llm-chain-llama/src/model.rs
- crates/llm-chain-llama/src/options.rs
- crates/llm-chain/src/options.rs
This only affects if using CUDA with llama.cpp.
Passing in a empty vector (instead of null) to `tensor_split` into the model parameters causes it to segfault. Passing a nullptr is fine and will cause llama.cpp use some default settings for `tensor_split`. Passing a empty vector by `Vec::new()` doesn't allocate any memory but also isn't a nullptr, it goes to `0x04` for some reason, then the c++ code in llama.cpp only check is `== nullptr` which `0x04` passes and then causes llama.cpp to segfault.
Make the tensor_split an `Option<Vec<32>>` works better since then you can just pass in a `null` for the `None` case.
> fix segfault in tensor split

- crates/llm-chain/src/traits.rs
I moved the `Sized` bound from the Executor trait to the two initializer methods. This makes the [trait object safe](https://doc.rust-lang.org/reference/items/traits.html#object-safety), allowing for the following
```rust
struct Context {
engine: Arc<dyn Executor>
}
```
> feat: make Executor trait object safe

- crates/llm-chain-openai/src/lib.rs
I would like to propose exposing `async_openai` so that I can change the configuration from the outside e.g.
```rust
use llm_chain_openai::async_openai::{config::OpenAIConfig, Client};
#[tokio::main(flavor = "current_thread")]
async fn main() {
let cfg: OpenAIConfig = OpenAIConfig::new()
.with_api_base("https://openrouter.ai/api/v1")
.with_api_key("sk-xxx");
let open_router_ai_client = Client::with_config(cfg);
let model = "text-embedding-ada-002";
let embeddings =
llm_chain_openai::embeddings::Embeddings::for_client(open_router_ai_client, model);
}
```
FYI: https://openrouter.ai/ is drop in replacement for `OpenAI` with some free tier that easier to start with.
Not sure we need proper  `impl` for this or just expose `async_openai` but for present quick win I did choose to expose it first …
> feat: expose async_openai

- .github/workflows/cicd.yaml
> Revert "ci: drop protobuf, no longer needed by qdrant"

- crates/llm-chain-llama-sys/Cargo.toml
- crates/llm-chain-llama-sys/build.rs
- crates/llm-chain-llama/README.md
This commit removes the `cuda` feature and replaces it with an
environment variable `LLM_CHAIN_CUDA`.It also adds an additional
environment variable `LLM_CHAIN_CUDA_LIB_PATH` which should be set to
the path of the CUDA library directory, and include link libraries
required for CUDA. Finally `-fPIC` is added to `CMAKE_CUDA_FLAGS`.
The motivation for this is that having the feature `cuda` was not
working as this will cause the build to fail if infact the CUDA
library is not installed. I think that this may not have been the case
with earlier versions of llama.cpp and perhaps why this was not an
issue before.
> llama: replace cuda feature with env var

- crates/llm-chain-openai/src/chatgpt/executor.rs
This commit adds support for setting the base url for the openai client. This is useful for testing and for using the client with a different provider.
The motivation for this came from wanting to try out Perplexities API using `llm-chain-openai`. For this I needed to set the base url to the one provided by Perplexity, but I could find a way to that with the current implementation.
With the change in this commit, an example can be written like this:
```rust
use llm_chain::options;
use llm_chain::options::ModelRef;
use llm_chain::{executor, parameters, prompt};
async fn main() -> Result<(), Box<dyn std::error::Error>> {
let opts = options!(
Model: ModelRef::from_model_name("pplx-70b-online")
);
let exec = executor!(chatgpt, opts.clone())?;
let query = "What is the capital of Sweden?"; …
```
> openai: add support for setting the base url

- Cargo.lock
- crates/llm-chain-llama-sys/README.md
This commit updates the README.md file for the llm-chain-llama-sys crate to reflect the correct name of the crate.
The motivation for this is that the readme on crates.io might be confusing at the moment:
https://crates.io/crates/llm-chain-llama-sys
> docs: update llm-chain-llama-sys README.md

- docs/CONTRIBUTING.md
Addresses https://github.com/sobelio/llm-chain/issues/248
> Fix: Compile Failed for llm-chain-llama-sys & llm-chain-llama #248

- website/docs/getting-started-tutorial/02-generating-your-first-llm-output.md
Good Morning Sir, 
I have been exploring the llm-chains project and, although I am new to Rust (just started learning about 4 hours ago through a tutorial), I found something that might be useful. I noticed that the current instructions suggest setting a single API key as an environment variable. However, I needed to implement a round-robin mechanism to use a cluster of API keys.
While reviewing the code, I found guidance on how to do this in the comment section, which was very helpful. I believe that adding this information to the documentation would make it more accessible to other users.
Therefore, I have updated the documentation to include instructions on setting up and using multiple API keys. I hope you find this addition valuable and that it will be merged into the main branch. …
> Updated Docs, adding information about how use apikey without enviroment variable.
