sobelio/llm-chain

llm-chain-tools/examples/simple_agent.rs, llm-chain-tools/src/collection.rs, llm-chain/Cargo.toml, llm-chain/src/lib.rs, llm-chain/src/parsing.rs
=> Implement centralized parsing for LLM outputs.

docs/CONTRIBUTING.md, website/docs/development-setup.md
- Added some more steps to include how to setup the local dev environment 
- Copied it to a new development setup page on the website
=> docs: add local dev env setup for contributions

.github/workflows/cicd.yaml
=> ci: test on ubuntu, macos and windows

llm-chain-llama/src/step.rs, llm-chain-openai/src/chatgpt/prompt.rs, llm-chain/Cargo.toml, llm-chain/src/parameters.rs, llm-chain/src/templates/legacy.rs, llm-chain/src/templates/mod.rs, llm-chain/src/templates/tera.rs
- Handle static string templates.
- test: Add @ssoudan 's test for prompt template breakage
- Add Tera support for prompt templates
=> 36 revamp prompt template system

llm-chain-openai/Cargo.toml, llm-chain-openai/examples/qdrant_vectorstore.rs, llm-chain-openai/examples/simple_embeddings.rs, llm-chain-openai/src/embeddings.rs, llm-chain-openai/src/lib.rs, llm-chain/Cargo.toml, llm-chain/src/lib.rs, llm-chain/src/tokens.rs, llm-chain/src/traits.rs, llm-chain/src/vectorstores/mod.rs, llm-chain/src/vectorstores/qdrant.rs
Add embeddings and vectorstore trait to llm-chain; only add_texts methods supported; implement Qdrant vectorstore; implement OpenAI embeddings
=> Feature: Add texts to vectorstore

llm-chain-openai/Cargo.toml, llm-chain/Cargo.toml, llm-chain/src/templates/mod.rs, llm-chain/src/vectorstores/mod.rs
=> Make Tera and Qdrant optional dependencies

llm-chain-llama/src/instruct.rs, llm-chain-llama/src/step.rs, llm-chain-openai/examples/simple_agent.rs, llm-chain-openai/examples/simple_invocation.rs, llm-chain-openai/src/chatgpt/executor.rs, llm-chain-openai/src/chatgpt/prompt.rs, llm-chain-openai/src/chatgpt/step.rs, llm-chain/examples/tools_prompt.rs, llm-chain/src/lib.rs, llm-chain/src/templates/error.rs, llm-chain/src/templates/legacy.rs, llm-chain/src/templates/mod.rs
This is not yet a breaking change but once we make steps return Result
it will be a breaking one.
=> refactor: PromptTemplates now return Result

docs/CHANGELOG.md, llm-chain-llama/examples/alpaca.rs, llm-chain-llama/examples/simple.rs, llm-chain-llama/examples/stream.rs, llm-chain-llama/src/executor.rs, llm-chain-llama/src/step.rs, llm-chain-openai/examples/simple_agent.rs, llm-chain-openai/examples/simple_invocation.rs, llm-chain-openai/src/chatgpt/executor.rs, llm-chain-openai/src/chatgpt/step.rs, llm-chain/src/chains/map_reduce.rs, llm-chain/src/chains/sequential.rs, llm-chain/src/frame.rs, llm-chain/src/traits.rs
This means that we have proper error handling all the way from model.
Hooray!
=> feat: All executors, step etc now return results.

docs/CHANGELOG.md, docs/README.md, llm-chain-openai/examples/generator_with_parameter.rs, llm-chain-openai/examples/map_reduce_long_article.rs, llm-chain-openai/examples/sequential_generation.rs, llm-chain-openai/examples/simple_generator.rs, website/docs/getting-started-tutorial/02-generating-your-first-llm-output.md, website/docs/getting-started-tutorial/03-using-prompt-templates-and-parameters.md, website/docs/getting-started-tutorial/04-building-a-multi-step-chain.md, website/docs/getting-started-tutorial/05-summarizing-text-with-map-reduce.md
- docs: prepare for 0.6.0
- docs: changelog for 0.6.0
=> prepare docs 0.6.0

llm-chain/src/lib.rs, llm-chain/src/summarization.rs
Added an opinionated summarization module that can be used to quickly get started with summarization.
=> feat: add summarization module

llm-chain-openai/src/chatgpt/output.rs, llm-chain-openai/src/chatgpt/text_splitter.rs, llm-chain/src/chains/mod.rs, llm-chain/src/chains/sequential.rs, llm-chain/src/executor.rs, llm-chain/src/output.rs, llm-chain/src/parameters.rs, llm-chain/src/parsing.rs, llm-chain/src/schema.rs, llm-chain/src/step.rs, llm-chain/src/summarization.rs, llm-chain/src/text_splitter.rs, llm-chain/src/tools/tool.rs, llm-chain/src/tools/tools/vectorstore.rs, llm-chain/src/traits.rs, llm-chain/src/vectorstores/mod.rs
- docs: update doc summary-lines
- docs: add summaries to all modules
- docs: add docs for sequential chain
=> docs update

docs/CHANGELOG.md, llm-chain/src/traits.rs, website/docs/getting-started-tutorial/02-generating-your-first-llm-output.md, website/docs/getting-started-tutorial/03-using-prompt-templates-and-parameters.md, website/docs/getting-started-tutorial/04-building-a-multi-step-chain.md, website/docs/getting-started-tutorial/05-summarizing-text-with-map-reduce.md
- remove unused traits
- update docs for 0.8
- update change log
=> Prepare for 0.8.0 release

Cargo.lock, llm-chain/Cargo.toml, llm-chain/examples/bing_search.rs, llm-chain/src/tools/tools/bing_search.rs, llm-chain/src/tools/tools/mod.rs
Existing Bing API wrapper libraries on crates.io don't seem like they are being maintained.
This should be replaced as soon as a solid Bing API client library emerges
=> Feature: Bing Search tool

llm-chain/src/chains/conversation.rs
It is useful to be able to save & reload conversations.
=> derive Serialize, Deserialize for conversation

llm-chain-openai/src/chatgpt/executor.rs
fixes #118
fix the issue where the Executor returned by for_client didn't implement the Executor type
the `new_with_options` function will set the clients org_id if a OPENAI_ORG_ID environment variable is present
=> llm-chain-openai: fix #118, and support organization IDs

.github/workflows/cicd.yaml, llm-chain-llama/examples/few_shot.rs, llm-chain-llama/src/context.rs, llm-chain-llama/src/executor.rs, llm-chain-llama/src/options.rs, llm-chain-openai/src/chatgpt/executor.rs, llm-chain/src/agents/self_ask_with_search.rs, llm-chain/src/chains/map_reduce.rs, llm-chain/src/tokens.rs, llm-chain/src/traits.rs
I just ran cargo fmt --all, nothing special here
This should be merged after #119 because both change the executor file, and if there are any conflicts I'd want to resolve them here.
=> chore: cargo fmt

llm-chain-llama/examples/few_shot.rs, llm-chain-llama/src/context.rs, llm-chain-llama/src/executor.rs, llm-chain-llama/src/options.rs, llm-chain-llama/sys/build.rs, llm-chain-openai/src/chatgpt/options.rs, llm-chain-qdrant/src/lib.rs, llm-chain/src/agents/self_ask_with_search.rs, llm-chain/src/chains/conversation.rs, llm-chain/src/chains/map_reduce.rs, llm-chain/src/parsing.rs, llm-chain/src/prompt/chat.rs, llm-chain/src/step.rs, llm-chain/src/tokens.rs, llm-chain/src/tools/collection.rs, llm-chain/src/tools/mod.rs, llm-chain/src/tools/tools/bing_search.rs, llm-chain/src/traits.rs
This PR fixes various clippy lints
I first ran cargo clippy --fix, then fixed remaining lints manually
this is both non-essential and should be reviewed before merging, because it changes a bunch of files and could cause conflicts with stuff other people are working on
=> Chore: cargo clippy

crates/llm-chain-llama-sys/Cargo.toml, crates/llm-chain-llama-sys/build.rs
https://github.com/ggerganov/llama.cpp#cublas
Gated by Rust feature.
=> feat: enable GPU acceleration through CUDA using cuBLAS

Cargo.lock, crates/llm-chain-macros/Cargo.toml, crates/llm-chain-macros/src/lib.rs, crates/llm-chain-macros/src/main.rs, crates/llm-chain/Cargo.toml, crates/llm-chain/examples/tool_derive_describe.rs
Added a proc-macro that derives the Describe trait for Tool inputs and outputs
=> Derive describe

crates/llm-chain-openai/src/chatgpt/executor.rs
fixes #164
A hack, we should raise an issue for tiktoken
=> fix: change type and function to calc tokens in message

crates/llm-chain-llama-sys/build.rs, crates/llm-chain-llama/src/context.rs
Bindings didn't work right when the cuda feature was enabled.
https://github.com/sobelio/llm-chain/issues/174
=> fixed CUBLAS bindings and hardcoded LLAMA_MAX_DEVICES

website/docs/development-setup.md
More precise git submodule command on fetching submodules, for those never used it before, like me.
An explanation of git submodule commands: [link](https://stackoverflow.com/questions/29971374/difference-between-git-submodule-init-git-submodule-update-and-git-submodu)
=> fix: better git submodule command in docs

crates/llm-chain-llama/examples/few_shot.rs, crates/llm-chain-llama/src/executor.rs, crates/llm-chain-llama/src/options.rs, crates/llm-chain/src/options.rs
Added some error handling for opt_extract
Not getting the env variables to work though. I'm assuming it has something with the model not being a string @williamhogman, maybe you can help me out here?
=> opt_extract returns result

crates/llm-chain-local/README.md
Makes it easier for first-time user to navigate the codebase.
=> Create README.md for llm-chain-local

website/docs/llama-tutorial.md
This is a version of the tutorial using the LLAMA driver instead of the OpenAI driver.
=> docs: llama driver tutorial

crates/llm-chain-mock/examples/simple.rs, crates/llm-chain-mock/src/executor.rs, crates/llm-chain-sagemaker-endpoint/CHANGELOG.md, crates/llm-chain-sagemaker-endpoint/Cargo.toml, crates/llm-chain-sagemaker-endpoint/README.md, crates/llm-chain-sagemaker-endpoint/examples/simple.rs, crates/llm-chain-sagemaker-endpoint/src/executor.rs, crates/llm-chain-sagemaker-endpoint/src/lib.rs, crates/llm-chain-sagemaker-endpoint/src/model.rs, crates/llm-chain/src/executor.rs, crates/llm-chain/src/options.rs
This driver allows you to invoke LLMs running on Amazon SageMaker Endpoint, including SageMaker JumpStart models. See the README for a getting started guide.
=> Amazon SageMaker Endpoint Driver

website/docs/llama-tutorial.md
Under Linux, the command didn't work as it was originally.
=> Fix a command on a website

crates/llm-chain-qdrant/examples/qdrant_vectorstore.rs, crates/llm-chain-qdrant/examples/similarity_search.rs, crates/llm-chain-qdrant/examples/vectorstore_tool_invocation.rs, crates/llm-chain-qdrant/src/lib.rs
Adds support for setting qdrant filters that will be used when retrieving documents
This is a breaking change
Closes #228
=> Qdrant VectorStore: added ability to set search filters

crates/llm-chain-llama/examples/few_shot.rs, crates/llm-chain-llama/src/executor.rs
This commit changes the `LLamaTokenizer` to use
`tokio::task::block_in_place` in an attempt avoid the following error:
```console
$ env RUST_BACKTRACE=1 \
LLM_CHAIN_MODEL=models/llama-2-7b-chat.ggmlv3.q4_0.bin \
cargo r --example few_shot
thread 'main' panicked at
'Cannot block the current thread from within a runtime. This happens
because a function attempted to block the current thread while the
thread is being used to drive asynchronous tasks.',
crates/llm-chain-llama/src/executor.rs:290:36
stack backtrace:
0: rust_begin_unwind
at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
1: core::panicking::panic_fmt
at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
2: core::panicking::panic_display
at …
```
=> fix: use block_in_place in llama tokenizer

crates/llm-chain/src/agents/self_ask_with_search.rs
Added documentation to the existing agent. Eventually the common structures will need to be refactored for reusability.
=> Added documentation to 'agents/self_ask_with_search.rs'

website/docs/chains/02-map-reduce-chains.md, website/docs/getting-started-tutorial/01-setting-up-a-project.md, website/docs/getting-started-tutorial/02-generating-your-first-llm-output.md, website/docs/getting-started-tutorial/03-using-prompt-templates-and-parameters.md, website/docs/getting-started-tutorial/04-building-a-multi-step-chain.md, website/docs/getting-started-tutorial/05-summarizing-text-with-map-reduce.md
Some super minor grammar fixes for the docs. Thank you for building this.
=> fix(docs): minor grammar fixes
